// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > src/lib/supabase/database.types.ts
// For now, this is a placeholder with manual types matching our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string;
          role: "admin" | "sponsor" | "judge" | "participant";
          avatar: string | null;
          wallet_address: string | null;
          bio: string | null;
          twitter: string | null;
          github: string | null;
          sponsor_org_id: string | null;
          has_completed_onboarding: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          name: string;
          role?: "admin" | "sponsor" | "judge" | "participant";
          avatar?: string | null;
          wallet_address?: string | null;
          bio?: string | null;
          twitter?: string | null;
          github?: string | null;
          sponsor_org_id?: string | null;
          has_completed_onboarding?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          role?: "admin" | "sponsor" | "judge" | "participant";
          avatar?: string | null;
          wallet_address?: string | null;
          bio?: string | null;
          twitter?: string | null;
          github?: string | null;
          sponsor_org_id?: string | null;
          has_completed_onboarding?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "users_sponsor_org_id_fkey";
            columns: ["sponsor_org_id"];
            isOneToOne: false;
            referencedRelation: "sponsor_orgs";
            referencedColumns: ["id"];
          }
        ];
      };
      cohorts: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          tagline: string | null;
          banner_image: string | null;
          start_date: string;
          end_date: string;
          submission_deadline: string;
          judging_start: string | null;
          judging_end: string | null;
          status: "draft" | "upcoming" | "active" | "judging" | "completed";
          is_public: boolean;
          max_team_size: number;
          prizes: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description: string;
          tagline?: string | null;
          banner_image?: string | null;
          start_date: string;
          end_date: string;
          submission_deadline: string;
          judging_start?: string | null;
          judging_end?: string | null;
          status?: "draft" | "upcoming" | "active" | "judging" | "completed";
          is_public?: boolean;
          max_team_size?: number;
          prizes?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          tagline?: string | null;
          banner_image?: string | null;
          start_date?: string;
          end_date?: string;
          submission_deadline?: string;
          judging_start?: string | null;
          judging_end?: string | null;
          status?: "draft" | "upcoming" | "active" | "judging" | "completed";
          is_public?: boolean;
          max_team_size?: number;
          prizes?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sponsor_orgs: {
        Row: {
          id: string;
          name: string;
          logo: string | null;
          website: string | null;
          description: string | null;
          contact_name: string | null;
          contact_email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo?: string | null;
          website?: string | null;
          description?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          logo?: string | null;
          website?: string | null;
          description?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cohort_sponsors: {
        Row: {
          id: string;
          cohort_id: string;
          sponsor_org_id: string;
          tier: "platinum" | "gold" | "silver" | "bronze" | "community";
          prize_pool_contribution: number;
          has_dedicated_track: boolean;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          sponsor_org_id: string;
          tier: "platinum" | "gold" | "silver" | "bronze" | "community";
          prize_pool_contribution?: number;
          has_dedicated_track?: boolean;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          sponsor_org_id?: string;
          tier?: "platinum" | "gold" | "silver" | "bronze" | "community";
          prize_pool_contribution?: number;
          has_dedicated_track?: boolean;
          description?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "cohort_sponsors_cohort_id_fkey";
            columns: ["cohort_id"];
            isOneToOne: false;
            referencedRelation: "cohorts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "cohort_sponsors_sponsor_org_id_fkey";
            columns: ["sponsor_org_id"];
            isOneToOne: false;
            referencedRelation: "sponsor_orgs";
            referencedColumns: ["id"];
          }
        ];
      };
      tracks: {
        Row: {
          id: string;
          cohort_id: string;
          sponsor_org_id: string | null;
          name: string;
          description: string;
          prize_pool: string | null;
          requirements: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          sponsor_org_id?: string | null;
          name: string;
          description: string;
          prize_pool?: string | null;
          requirements?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          sponsor_org_id?: string | null;
          name?: string;
          description?: string;
          prize_pool?: string | null;
          requirements?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tracks_cohort_id_fkey";
            columns: ["cohort_id"];
            isOneToOne: false;
            referencedRelation: "cohorts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tracks_sponsor_org_id_fkey";
            columns: ["sponsor_org_id"];
            isOneToOne: false;
            referencedRelation: "sponsor_orgs";
            referencedColumns: ["id"];
          }
        ];
      };
      teams: {
        Row: {
          id: string;
          cohort_id: string;
          name: string;
          slug: string;
          description: string | null;
          logo_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          name: string;
          slug: string;
          description?: string | null;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "teams_cohort_id_fkey";
            columns: ["cohort_id"];
            isOneToOne: false;
            referencedRelation: "cohorts";
            referencedColumns: ["id"];
          }
        ];
      };
      team_members: {
        Row: {
          id: string;
          team_id: string;
          user_id: string;
          role: "lead" | "member";
          joined_at: string;
        };
        Insert: {
          id?: string;
          team_id: string;
          user_id: string;
          role?: "lead" | "member";
          joined_at?: string;
        };
        Update: {
          id?: string;
          team_id?: string;
          user_id?: string;
          role?: "lead" | "member";
          joined_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "team_members_team_id_fkey";
            columns: ["team_id"];
            isOneToOne: false;
            referencedRelation: "teams";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "team_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      team_invites: {
        Row: {
          id: string;
          team_id: string;
          email: string;
          invited_by: string;
          status: "pending" | "accepted" | "declined";
          created_at: string;
          expires_at: string;
        };
        Insert: {
          id?: string;
          team_id: string;
          email: string;
          invited_by: string;
          status?: "pending" | "accepted" | "declined";
          created_at?: string;
          expires_at: string;
        };
        Update: {
          id?: string;
          team_id?: string;
          email?: string;
          invited_by?: string;
          status?: "pending" | "accepted" | "declined";
          created_at?: string;
          expires_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "team_invites_team_id_fkey";
            columns: ["team_id"];
            isOneToOne: false;
            referencedRelation: "teams";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "team_invites_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      submissions: {
        Row: {
          id: string;
          cohort_id: string;
          team_id: string | null;
          created_by: string;
          title: string;
          tagline: string | null;
          description: string;
          demo_url: string | null;
          video_url: string | null;
          repo_url: string | null;
          presentation_url: string | null;
          screenshots: Json;
          tech_stack: Json;
          built_with_story: boolean;
          ip_asset_id: string | null;
          ip_registered_at: string | null;
          ip_license_type: "non-commercial" | "commercial-use" | "commercial-remix" | null;
          status: "draft" | "submitted" | "under_review" | "accepted" | "winner";
          submitted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          team_id?: string | null;
          created_by: string;
          title: string;
          tagline?: string | null;
          description: string;
          demo_url?: string | null;
          video_url?: string | null;
          repo_url?: string | null;
          presentation_url?: string | null;
          screenshots?: Json;
          tech_stack?: Json;
          built_with_story?: boolean;
          ip_asset_id?: string | null;
          ip_registered_at?: string | null;
          ip_license_type?: "non-commercial" | "commercial-use" | "commercial-remix" | null;
          status?: "draft" | "submitted" | "under_review" | "accepted" | "winner";
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          team_id?: string | null;
          created_by?: string;
          title?: string;
          tagline?: string | null;
          description?: string;
          demo_url?: string | null;
          video_url?: string | null;
          repo_url?: string | null;
          presentation_url?: string | null;
          screenshots?: Json;
          tech_stack?: Json;
          built_with_story?: boolean;
          ip_asset_id?: string | null;
          ip_registered_at?: string | null;
          ip_license_type?: "non-commercial" | "commercial-use" | "commercial-remix" | null;
          status?: "draft" | "submitted" | "under_review" | "accepted" | "winner";
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "submissions_cohort_id_fkey";
            columns: ["cohort_id"];
            isOneToOne: false;
            referencedRelation: "cohorts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "submissions_team_id_fkey";
            columns: ["team_id"];
            isOneToOne: false;
            referencedRelation: "teams";
            referencedColumns: ["id"];
          }
        ];
      };
      submission_tracks: {
        Row: {
          id: string;
          submission_id: string;
          track_id: string;
        };
        Insert: {
          id?: string;
          submission_id: string;
          track_id: string;
        };
        Update: {
          id?: string;
          submission_id?: string;
          track_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "submission_tracks_submission_id_fkey";
            columns: ["submission_id"];
            isOneToOne: false;
            referencedRelation: "submissions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "submission_tracks_track_id_fkey";
            columns: ["track_id"];
            isOneToOne: false;
            referencedRelation: "tracks";
            referencedColumns: ["id"];
          }
        ];
      };
      reviews: {
        Row: {
          id: string;
          submission_id: string;
          judge_id: string;
          innovation_score: number | null;
          execution_score: number | null;
          design_score: number | null;
          impact_score: number | null;
          presentation_score: number | null;
          overall_score: number | null;
          feedback: string | null;
          internal_notes: string | null;
          status: "pending" | "in_progress" | "completed";
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          submission_id: string;
          judge_id: string;
          innovation_score?: number | null;
          execution_score?: number | null;
          design_score?: number | null;
          impact_score?: number | null;
          presentation_score?: number | null;
          overall_score?: number | null;
          feedback?: string | null;
          internal_notes?: string | null;
          status?: "pending" | "in_progress" | "completed";
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          submission_id?: string;
          judge_id?: string;
          innovation_score?: number | null;
          execution_score?: number | null;
          design_score?: number | null;
          impact_score?: number | null;
          presentation_score?: number | null;
          overall_score?: number | null;
          feedback?: string | null;
          internal_notes?: string | null;
          status?: "pending" | "in_progress" | "completed";
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_submission_id_fkey";
            columns: ["submission_id"];
            isOneToOne: false;
            referencedRelation: "submissions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_judge_id_fkey";
            columns: ["judge_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      workshops: {
        Row: {
          id: string;
          title: string;
          description: string;
          content: string | null;
          video_url: string | null;
          article_url: string | null;
          partner_name: string | null;
          partner_logo: string | null;
          sponsor_org_id: string | null;
          host_id: string | null;
          category: string;
          duration: number | null;
          status: "draft" | "published" | "archived";
          published_at: string | null;
          is_evergreen: boolean;
          scheduled_at: string | null;
          end_time: string | null;
          timezone: string | null;
          is_live: boolean;
          max_attendees: number | null;
          location: string | null;
          meeting_url: string | null;
          recording_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          content?: string | null;
          video_url?: string | null;
          article_url?: string | null;
          partner_name?: string | null;
          partner_logo?: string | null;
          sponsor_org_id?: string | null;
          host_id?: string | null;
          category: string;
          duration?: number | null;
          status?: "draft" | "published" | "archived";
          published_at?: string | null;
          is_evergreen?: boolean;
          scheduled_at?: string | null;
          end_time?: string | null;
          timezone?: string | null;
          is_live?: boolean;
          max_attendees?: number | null;
          location?: string | null;
          meeting_url?: string | null;
          recording_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          content?: string | null;
          video_url?: string | null;
          article_url?: string | null;
          partner_name?: string | null;
          partner_logo?: string | null;
          sponsor_org_id?: string | null;
          host_id?: string | null;
          category?: string;
          duration?: number | null;
          status?: "draft" | "published" | "archived";
          published_at?: string | null;
          is_evergreen?: boolean;
          scheduled_at?: string | null;
          end_time?: string | null;
          timezone?: string | null;
          is_live?: boolean;
          max_attendees?: number | null;
          location?: string | null;
          meeting_url?: string | null;
          recording_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "workshops_sponsor_org_id_fkey";
            columns: ["sponsor_org_id"];
            isOneToOne: false;
            referencedRelation: "sponsor_orgs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "workshops_host_id_fkey";
            columns: ["host_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      workshop_cohorts: {
        Row: {
          id: string;
          workshop_id: string;
          cohort_id: string;
        };
        Insert: {
          id?: string;
          workshop_id: string;
          cohort_id: string;
        };
        Update: {
          id?: string;
          workshop_id?: string;
          cohort_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "workshop_cohorts_workshop_id_fkey";
            columns: ["workshop_id"];
            isOneToOne: false;
            referencedRelation: "workshops";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "workshop_cohorts_cohort_id_fkey";
            columns: ["cohort_id"];
            isOneToOne: false;
            referencedRelation: "cohorts";
            referencedColumns: ["id"];
          }
        ];
      };
      workshop_rsvps: {
        Row: {
          id: string;
          workshop_id: string;
          user_id: string;
          status: "registered" | "attended" | "cancelled";
          registered_at: string;
          attended_at: string | null;
        };
        Insert: {
          id?: string;
          workshop_id: string;
          user_id: string;
          status?: "registered" | "attended" | "cancelled";
          registered_at?: string;
          attended_at?: string | null;
        };
        Update: {
          id?: string;
          workshop_id?: string;
          user_id?: string;
          status?: "registered" | "attended" | "cancelled";
          registered_at?: string;
          attended_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "workshop_rsvps_workshop_id_fkey";
            columns: ["workshop_id"];
            isOneToOne: false;
            referencedRelation: "workshops";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "workshop_rsvps_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      workshop_versions: {
        Row: {
          id: string;
          workshop_id: string;
          title: string;
          content: string;
          author_id: string;
          change_note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workshop_id: string;
          title: string;
          content: string;
          author_id: string;
          change_note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workshop_id?: string;
          title?: string;
          content?: string;
          author_id?: string;
          change_note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "workshop_versions_workshop_id_fkey";
            columns: ["workshop_id"];
            isOneToOne: false;
            referencedRelation: "workshops";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "workshop_versions_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      media_assets: {
        Row: {
          id: string;
          filename: string;
          url: string;
          mime_type: string;
          size: number;
          uploaded_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          filename: string;
          url: string;
          mime_type: string;
          size: number;
          uploaded_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          filename?: string;
          url?: string;
          mime_type?: string;
          size?: number;
          uploaded_by?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "media_assets_uploaded_by_fkey";
            columns: ["uploaded_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      templates: {
        Row: {
          id: string;
          submission_id: string | null;
          title: string;
          description: string;
          category: string;
          tags: Json;
          ip_asset_id: string | null;
          fork_count: number;
          is_featured: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          submission_id?: string | null;
          title: string;
          description: string;
          category: string;
          tags?: Json;
          ip_asset_id?: string | null;
          fork_count?: number;
          is_featured?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          submission_id?: string | null;
          title?: string;
          description?: string;
          category?: string;
          tags?: Json;
          ip_asset_id?: string | null;
          fork_count?: number;
          is_featured?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "templates_submission_id_fkey";
            columns: ["submission_id"];
            isOneToOne: false;
            referencedRelation: "submissions";
            referencedColumns: ["id"];
          }
        ];
      };
      sponsor_invites: {
        Row: {
          id: string;
          token: string;
          sponsor_org_id: string;
          email: string | null;
          created_by: string;
          expires_at: string;
          used_at: string | null;
          used_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          token?: string;
          sponsor_org_id: string;
          email?: string | null;
          created_by: string;
          expires_at: string;
          used_at?: string | null;
          used_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          token?: string;
          sponsor_org_id?: string;
          email?: string | null;
          created_by?: string;
          expires_at?: string;
          used_at?: string | null;
          used_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "sponsor_invites_sponsor_org_id_fkey";
            columns: ["sponsor_org_id"];
            isOneToOne: false;
            referencedRelation: "sponsor_orgs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sponsor_invites_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sponsor_invites_used_by_fkey";
            columns: ["used_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      submission_traction: {
        Row: {
          id: string;
          submission_id: string;
          testnet_contract_address: string | null;
          mainnet_contract_address: string | null;
          contract_deployed_at: string | null;
          twitter_handle: string | null;
          twitter_user_id: string | null;
          website_url: string | null;
          ga_property_id: string | null;
          ga_refresh_token: string | null;
          ga_connected_at: string | null;
          ga_connected_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          submission_id: string;
          testnet_contract_address?: string | null;
          mainnet_contract_address?: string | null;
          contract_deployed_at?: string | null;
          twitter_handle?: string | null;
          twitter_user_id?: string | null;
          website_url?: string | null;
          ga_property_id?: string | null;
          ga_refresh_token?: string | null;
          ga_connected_at?: string | null;
          ga_connected_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          submission_id?: string;
          testnet_contract_address?: string | null;
          mainnet_contract_address?: string | null;
          contract_deployed_at?: string | null;
          twitter_handle?: string | null;
          twitter_user_id?: string | null;
          website_url?: string | null;
          ga_property_id?: string | null;
          ga_refresh_token?: string | null;
          ga_connected_at?: string | null;
          ga_connected_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "submission_traction_submission_id_fkey";
            columns: ["submission_id"];
            isOneToOne: true;
            referencedRelation: "submissions";
            referencedColumns: ["id"];
          }
        ];
      };
      traction_snapshots: {
        Row: {
          id: string;
          submission_id: string;
          snapshot_date: string;
          reported_dau: number | null;
          reported_mau: number | null;
          reported_monthly_visits: number | null;
          onchain_tx_count: number | null;
          onchain_unique_addresses: number | null;
          onchain_tvl_usd: number | null;
          twitter_followers: number | null;
          twitter_impressions_7d: number | null;
          twitter_engagement_7d: number | null;
          ga_active_users: number | null;
          ga_total_users: number | null;
          ga_sessions: number | null;
          ga_pageviews: number | null;
          ga_bounce_rate: number | null;
          ga_avg_session_duration: number | null;
          data_source: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          submission_id: string;
          snapshot_date: string;
          reported_dau?: number | null;
          reported_mau?: number | null;
          reported_monthly_visits?: number | null;
          onchain_tx_count?: number | null;
          onchain_unique_addresses?: number | null;
          onchain_tvl_usd?: number | null;
          twitter_followers?: number | null;
          twitter_impressions_7d?: number | null;
          twitter_engagement_7d?: number | null;
          ga_active_users?: number | null;
          ga_total_users?: number | null;
          ga_sessions?: number | null;
          ga_pageviews?: number | null;
          ga_bounce_rate?: number | null;
          ga_avg_session_duration?: number | null;
          data_source?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          submission_id?: string;
          snapshot_date?: string;
          reported_dau?: number | null;
          reported_mau?: number | null;
          reported_monthly_visits?: number | null;
          onchain_tx_count?: number | null;
          onchain_unique_addresses?: number | null;
          onchain_tvl_usd?: number | null;
          twitter_followers?: number | null;
          twitter_impressions_7d?: number | null;
          twitter_engagement_7d?: number | null;
          ga_active_users?: number | null;
          ga_total_users?: number | null;
          ga_sessions?: number | null;
          ga_pageviews?: number | null;
          ga_bounce_rate?: number | null;
          ga_avg_session_duration?: number | null;
          data_source?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "traction_snapshots_submission_id_fkey";
            columns: ["submission_id"];
            isOneToOne: false;
            referencedRelation: "submissions";
            referencedColumns: ["id"];
          }
        ];
      };
      traction_milestones: {
        Row: {
          id: string;
          submission_id: string;
          milestone_type: "testnet_launch" | "mainnet_launch" | "first_100_users" | "first_1000_users" | "first_10000_users" | "funding_raised" | "partnership" | "media_feature" | "award" | "other";
          title: string;
          description: string | null;
          achieved_at: string;
          verified: boolean;
          verified_by: string | null;
          verified_at: string | null;
          proof_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          submission_id: string;
          milestone_type: "testnet_launch" | "mainnet_launch" | "first_100_users" | "first_1000_users" | "first_10000_users" | "funding_raised" | "partnership" | "media_feature" | "award" | "other";
          title: string;
          description?: string | null;
          achieved_at: string;
          verified?: boolean;
          verified_by?: string | null;
          verified_at?: string | null;
          proof_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          submission_id?: string;
          milestone_type?: "testnet_launch" | "mainnet_launch" | "first_100_users" | "first_1000_users" | "first_10000_users" | "funding_raised" | "partnership" | "media_feature" | "award" | "other";
          title?: string;
          description?: string | null;
          achieved_at?: string;
          verified?: boolean;
          verified_by?: string | null;
          verified_at?: string | null;
          proof_url?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "traction_milestones_submission_id_fkey";
            columns: ["submission_id"];
            isOneToOne: false;
            referencedRelation: "submissions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "traction_milestones_verified_by_fkey";
            columns: ["verified_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      user_role: {
        Args: Record<PropertyKey, never>;
        Returns: "admin" | "sponsor" | "judge" | "participant";
      };
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_sponsor: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_judge: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      user_sponsor_org_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      is_team_member: {
        Args: { team_id: string };
        Returns: boolean;
      };
      is_team_lead: {
        Args: { team_id: string };
        Returns: boolean;
      };
    };
    Enums: {
      user_role: "admin" | "sponsor" | "judge" | "participant";
      cohort_status: "draft" | "upcoming" | "active" | "judging" | "completed";
      submission_status: "draft" | "submitted" | "under_review" | "accepted" | "winner";
      review_status: "pending" | "in_progress" | "completed";
      workshop_status: "draft" | "published" | "archived";
      team_role: "lead" | "member";
      invite_status: "pending" | "accepted" | "declined";
      sponsor_tier: "platinum" | "gold" | "silver" | "bronze" | "community";
      rsvp_status: "registered" | "attended" | "cancelled";
      ip_license_type: "non-commercial" | "commercial-use" | "commercial-remix";
      milestone_type: "testnet_launch" | "mainnet_launch" | "first_100_users" | "first_1000_users" | "first_10000_users" | "funding_raised" | "partnership" | "media_feature" | "award" | "other";
    };
    CompositeTypes: Record<string, never>;
  };
};

// Type helpers for common operations
type PublicSchema = Database["public"];

export type Tables<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
  ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
      Row: infer R;
    }
    ? R
    : never
  : never;

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
  ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
      Insert: infer I;
    }
    ? I
    : never
  : never;

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
  ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
      Update: infer U;
    }
    ? U
    : never
  : never;

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof PublicSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema["Enums"]
  ? PublicSchema["Enums"][PublicEnumNameOrOptions]
  : never;
