// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > src/lib/supabase/database.types.ts
// For now, this is a placeholder with manual types matching our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string;
          role: "admin" | "sponsor" | "judge" | "participant";
          avatar: string | null;
          wallet_address: string | null;
          bio: string | null;
          twitter: string | null;
          github: string | null;
          sponsor_org_id: string | null;
          has_completed_onboarding: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          name: string;
          role?: "admin" | "sponsor" | "judge" | "participant";
          avatar?: string | null;
          wallet_address?: string | null;
          bio?: string | null;
          twitter?: string | null;
          github?: string | null;
          sponsor_org_id?: string | null;
          has_completed_onboarding?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          role?: "admin" | "sponsor" | "judge" | "participant";
          avatar?: string | null;
          wallet_address?: string | null;
          bio?: string | null;
          twitter?: string | null;
          github?: string | null;
          sponsor_org_id?: string | null;
          has_completed_onboarding?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      cohorts: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          tagline: string | null;
          banner_image: string | null;
          start_date: string;
          end_date: string;
          submission_deadline: string;
          judging_start: string | null;
          judging_end: string | null;
          status: "draft" | "upcoming" | "active" | "judging" | "completed";
          is_public: boolean;
          max_team_size: number;
          prizes: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description: string;
          tagline?: string | null;
          banner_image?: string | null;
          start_date: string;
          end_date: string;
          submission_deadline: string;
          judging_start?: string | null;
          judging_end?: string | null;
          status?: "draft" | "upcoming" | "active" | "judging" | "completed";
          is_public?: boolean;
          max_team_size?: number;
          prizes?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          tagline?: string | null;
          banner_image?: string | null;
          start_date?: string;
          end_date?: string;
          submission_deadline?: string;
          judging_start?: string | null;
          judging_end?: string | null;
          status?: "draft" | "upcoming" | "active" | "judging" | "completed";
          is_public?: boolean;
          max_team_size?: number;
          prizes?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      sponsor_orgs: {
        Row: {
          id: string;
          name: string;
          logo: string | null;
          website: string | null;
          description: string | null;
          contact_name: string | null;
          contact_email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo?: string | null;
          website?: string | null;
          description?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          logo?: string | null;
          website?: string | null;
          description?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      cohort_sponsors: {
        Row: {
          id: string;
          cohort_id: string;
          sponsor_org_id: string;
          tier: "platinum" | "gold" | "silver" | "bronze" | "community";
          prize_pool_contribution: number;
          has_dedicated_track: boolean;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          sponsor_org_id: string;
          tier: "platinum" | "gold" | "silver" | "bronze" | "community";
          prize_pool_contribution?: number;
          has_dedicated_track?: boolean;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          sponsor_org_id?: string;
          tier?: "platinum" | "gold" | "silver" | "bronze" | "community";
          prize_pool_contribution?: number;
          has_dedicated_track?: boolean;
          description?: string | null;
          created_at?: string;
        };
      };
      tracks: {
        Row: {
          id: string;
          cohort_id: string;
          sponsor_org_id: string | null;
          name: string;
          description: string;
          prize_pool: string | null;
          requirements: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          sponsor_org_id?: string | null;
          name: string;
          description: string;
          prize_pool?: string | null;
          requirements?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          sponsor_org_id?: string | null;
          name?: string;
          description?: string;
          prize_pool?: string | null;
          requirements?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      teams: {
        Row: {
          id: string;
          cohort_id: string;
          name: string;
          slug: string;
          description: string | null;
          logo_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          name: string;
          slug: string;
          description?: string | null;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      team_members: {
        Row: {
          id: string;
          team_id: string;
          user_id: string;
          role: "lead" | "member";
          joined_at: string;
        };
        Insert: {
          id?: string;
          team_id: string;
          user_id: string;
          role?: "lead" | "member";
          joined_at?: string;
        };
        Update: {
          id?: string;
          team_id?: string;
          user_id?: string;
          role?: "lead" | "member";
          joined_at?: string;
        };
      };
      team_invites: {
        Row: {
          id: string;
          team_id: string;
          email: string;
          invited_by: string;
          status: "pending" | "accepted" | "declined";
          created_at: string;
          expires_at: string;
        };
        Insert: {
          id?: string;
          team_id: string;
          email: string;
          invited_by: string;
          status?: "pending" | "accepted" | "declined";
          created_at?: string;
          expires_at: string;
        };
        Update: {
          id?: string;
          team_id?: string;
          email?: string;
          invited_by?: string;
          status?: "pending" | "accepted" | "declined";
          created_at?: string;
          expires_at?: string;
        };
      };
      submissions: {
        Row: {
          id: string;
          cohort_id: string;
          team_id: string;
          title: string;
          tagline: string | null;
          description: string;
          demo_url: string | null;
          video_url: string | null;
          repo_url: string | null;
          presentation_url: string | null;
          screenshots: Json;
          tech_stack: Json;
          built_with_story: boolean;
          ip_asset_id: string | null;
          ip_registered_at: string | null;
          ip_license_type: "non-commercial" | "commercial-use" | "commercial-remix" | null;
          status: "draft" | "submitted" | "under_review" | "accepted" | "winner";
          submitted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          team_id: string;
          title: string;
          tagline?: string | null;
          description: string;
          demo_url?: string | null;
          video_url?: string | null;
          repo_url?: string | null;
          presentation_url?: string | null;
          screenshots?: Json;
          tech_stack?: Json;
          built_with_story?: boolean;
          ip_asset_id?: string | null;
          ip_registered_at?: string | null;
          ip_license_type?: "non-commercial" | "commercial-use" | "commercial-remix" | null;
          status?: "draft" | "submitted" | "under_review" | "accepted" | "winner";
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          team_id?: string;
          title?: string;
          tagline?: string | null;
          description?: string;
          demo_url?: string | null;
          video_url?: string | null;
          repo_url?: string | null;
          presentation_url?: string | null;
          screenshots?: Json;
          tech_stack?: Json;
          built_with_story?: boolean;
          ip_asset_id?: string | null;
          ip_registered_at?: string | null;
          ip_license_type?: "non-commercial" | "commercial-use" | "commercial-remix" | null;
          status?: "draft" | "submitted" | "under_review" | "accepted" | "winner";
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      submission_tracks: {
        Row: {
          id: string;
          submission_id: string;
          track_id: string;
        };
        Insert: {
          id?: string;
          submission_id: string;
          track_id: string;
        };
        Update: {
          id?: string;
          submission_id?: string;
          track_id?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          submission_id: string;
          judge_id: string;
          innovation_score: number | null;
          execution_score: number | null;
          design_score: number | null;
          impact_score: number | null;
          presentation_score: number | null;
          overall_score: number | null;
          feedback: string | null;
          internal_notes: string | null;
          status: "pending" | "in_progress" | "completed";
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          submission_id: string;
          judge_id: string;
          innovation_score?: number | null;
          execution_score?: number | null;
          design_score?: number | null;
          impact_score?: number | null;
          presentation_score?: number | null;
          overall_score?: number | null;
          feedback?: string | null;
          internal_notes?: string | null;
          status?: "pending" | "in_progress" | "completed";
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          submission_id?: string;
          judge_id?: string;
          innovation_score?: number | null;
          execution_score?: number | null;
          design_score?: number | null;
          impact_score?: number | null;
          presentation_score?: number | null;
          overall_score?: number | null;
          feedback?: string | null;
          internal_notes?: string | null;
          status?: "pending" | "in_progress" | "completed";
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      workshops: {
        Row: {
          id: string;
          title: string;
          description: string;
          content: string | null;
          video_url: string | null;
          article_url: string | null;
          partner_name: string | null;
          partner_logo: string | null;
          sponsor_org_id: string | null;
          created_by: string | null;
          category: string;
          duration: string | null;
          status: "draft" | "published" | "archived";
          published_at: string | null;
          is_evergreen: boolean;
          scheduled_at: string | null;
          end_time: string | null;
          timezone: string | null;
          is_live: boolean;
          max_attendees: number | null;
          location: string | null;
          meeting_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          content?: string | null;
          video_url?: string | null;
          article_url?: string | null;
          partner_name?: string | null;
          partner_logo?: string | null;
          sponsor_org_id?: string | null;
          created_by?: string | null;
          category: string;
          duration?: string | null;
          status?: "draft" | "published" | "archived";
          published_at?: string | null;
          is_evergreen?: boolean;
          scheduled_at?: string | null;
          end_time?: string | null;
          timezone?: string | null;
          is_live?: boolean;
          max_attendees?: number | null;
          location?: string | null;
          meeting_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          content?: string | null;
          video_url?: string | null;
          article_url?: string | null;
          partner_name?: string | null;
          partner_logo?: string | null;
          sponsor_org_id?: string | null;
          created_by?: string | null;
          category?: string;
          duration?: string | null;
          status?: "draft" | "published" | "archived";
          published_at?: string | null;
          is_evergreen?: boolean;
          scheduled_at?: string | null;
          end_time?: string | null;
          timezone?: string | null;
          is_live?: boolean;
          max_attendees?: number | null;
          location?: string | null;
          meeting_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      workshop_cohorts: {
        Row: {
          id: string;
          workshop_id: string;
          cohort_id: string;
        };
        Insert: {
          id?: string;
          workshop_id: string;
          cohort_id: string;
        };
        Update: {
          id?: string;
          workshop_id?: string;
          cohort_id?: string;
        };
      };
      workshop_rsvps: {
        Row: {
          id: string;
          workshop_id: string;
          user_id: string;
          status: "registered" | "attended" | "cancelled";
          registered_at: string;
          attended_at: string | null;
        };
        Insert: {
          id?: string;
          workshop_id: string;
          user_id: string;
          status?: "registered" | "attended" | "cancelled";
          registered_at?: string;
          attended_at?: string | null;
        };
        Update: {
          id?: string;
          workshop_id?: string;
          user_id?: string;
          status?: "registered" | "attended" | "cancelled";
          registered_at?: string;
          attended_at?: string | null;
        };
      };
      workshop_versions: {
        Row: {
          id: string;
          workshop_id: string;
          title: string;
          content: string;
          author_id: string;
          change_note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workshop_id: string;
          title: string;
          content: string;
          author_id: string;
          change_note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workshop_id?: string;
          title?: string;
          content?: string;
          author_id?: string;
          change_note?: string | null;
          created_at?: string;
        };
      };
      media_assets: {
        Row: {
          id: string;
          filename: string;
          url: string;
          mime_type: string;
          size: number;
          uploaded_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          filename: string;
          url: string;
          mime_type: string;
          size: number;
          uploaded_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          filename?: string;
          url?: string;
          mime_type?: string;
          size?: number;
          uploaded_by?: string;
          created_at?: string;
        };
      };
      templates: {
        Row: {
          id: string;
          submission_id: string | null;
          title: string;
          description: string;
          category: string;
          tags: Json;
          ip_asset_id: string | null;
          fork_count: number;
          is_featured: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          submission_id?: string | null;
          title: string;
          description: string;
          category: string;
          tags?: Json;
          ip_asset_id?: string | null;
          fork_count?: number;
          is_featured?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          submission_id?: string | null;
          title?: string;
          description?: string;
          category?: string;
          tags?: Json;
          ip_asset_id?: string | null;
          fork_count?: number;
          is_featured?: boolean;
          created_at?: string;
        };
      };
    };
    Views: {};
    Functions: {
      user_role: {
        Args: Record<PropertyKey, never>;
        Returns: "admin" | "sponsor" | "judge" | "participant";
      };
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_sponsor: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_judge: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      user_sponsor_org_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      is_team_member: {
        Args: { team_id: string };
        Returns: boolean;
      };
      is_team_lead: {
        Args: { team_id: string };
        Returns: boolean;
      };
    };
    Enums: {
      user_role: "admin" | "sponsor" | "judge" | "participant";
      cohort_status: "draft" | "upcoming" | "active" | "judging" | "completed";
      submission_status: "draft" | "submitted" | "under_review" | "accepted" | "winner";
      review_status: "pending" | "in_progress" | "completed";
      workshop_status: "draft" | "published" | "archived";
      team_role: "lead" | "member";
      invite_status: "pending" | "accepted" | "declined";
      sponsor_tier: "platinum" | "gold" | "silver" | "bronze" | "community";
      rsvp_status: "registered" | "attended" | "cancelled";
      ip_license_type: "non-commercial" | "commercial-use" | "commercial-remix";
    };
  };
};
